#!/usr/bin/env python3
"""
Voice tests for customer-facing email copy generated by the pipeline:

- generate_personal_email() in intake_to_plan.py (the personalized day-1
  delivery email the webhook prefers when personal_email.md exists)
- EmailDelivery in email_delivery.py (legacy SendGrid/SMTP delivery path)

Brand voice contract: coach-to-athlete, specific, zero hype. No emoji,
no exclamation-point cheerleading, no slop phrases, signed
Matti / Gravel God Coaching.

Run with: pytest athletes/scripts/test_email_voice.py -v
"""

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent))

from intake_to_plan import generate_personal_email
from email_delivery import EmailDelivery
from deliver_package import _email_delivery_for_profile


BANNED_PHRASES = [
    'thrilled',
    'journey',
    'crush',
    'dive in',
    "let's dive",
    'amazing',
    'excited',
    "can't wait",
    'remember:',
    'no spam',
    # retired cringe from earlier copy revisions — must not come back
    'who you are as an athlete',
    'clear and achievable',
    'you know what it takes',
]


def _contains_emoji(text):
    for ch in text:
        cp = ord(ch)
        if 0x1F000 <= cp <= 0x1FFFF:
            return True
        if 0x2600 <= cp <= 0x27BF:
            return True
        if cp in (0xFE0F, 0x200D):
            return True
    return False


def _assert_voice(text, label):
    lowered = text.lower()
    for phrase in BANNED_PHRASES:
        assert phrase not in lowered, f"banned phrase {phrase!r} in {label}"
    assert not _contains_emoji(text), f"emoji in {label}"


@pytest.fixture
def profile():
    return {
        'name': 'Jesse Couch',
        'age': 52,
        'target_race': {
            'name': 'Unbound 200',
            'date': '2026-05-30',
            'goal_description': 'Finish under 14 hours',
        },
        'fitness_markers': {'ftp_watts': 245, 'ftp_estimated': True},
        'weekly_availability': {'cycling_hours_target': 8},
        'training_history': {'years_cycling': 12},
        'health_factors': {'stress_level': 'high', 'sleep_hours_avg': '6-7'},
        'injury_history': {'current_injuries': []},
        'strength': {'routine': '', 'include_in_plan': False},
        'preferred_days': {},
        'schedule_constraints': {},
        'blindspots': [],
        'notes': 'Worried about the Kansas heat.',
    }


@pytest.fixture
def parsed():
    return {
        'basic_info': {
            'primary_sport': 'running',
            'strengths': 'endurance engine, pacing',
        },
        'health': {'current_injuries': 'none'},
    }


class TestGeneratePersonalEmail:
    def test_voice_rules(self, profile, parsed):
        email = generate_personal_email(profile, parsed)
        _assert_voice(email, 'personal delivery email')

    def test_subject_is_plain_and_specific(self, profile, parsed):
        email = generate_personal_email(profile, parsed)
        subject_line = email.split('\n')[0]
        assert 'Unbound 200' in subject_line
        assert 'TrainingPeaks' in subject_line
        assert '!' not in subject_line

    def test_no_exclamation_cheerleading(self, profile, parsed):
        email = generate_personal_email(profile, parsed)
        assert '!' not in email

    def test_signed_matti_gravel_god_coaching(self, profile, parsed):
        email = generate_personal_email(profile, parsed)
        assert 'Matti' in email
        assert 'Gravel God Coaching' in email

    def test_references_athlete_specifics(self, profile, parsed):
        """The email must prove the coach read the questionnaire."""
        email = generate_personal_email(profile, parsed)
        assert '245' in email  # their FTP
        assert 'finish under 14 hours' in email.lower()  # their goal
        assert 'FTP test in Week 1' in email  # estimated FTP handling

    def test_has_trainingpeaks_cta_and_reply_invite(self, profile, parsed):
        email = generate_personal_email(profile, parsed)
        assert 'home.trainingpeaks.com/attachtocoach' in email
        assert 'reply to this email' in email.lower()

    def test_no_empty_flattery_without_goal(self, profile, parsed):
        """Without a goal the ack must not fall back to filler praise."""
        profile['target_race'].pop('goal_description')
        profile['target_race'].pop('goal', None)
        email = generate_personal_email(profile, parsed)
        _assert_voice(email, 'personal delivery email (no goal)')

    def test_roadie_signature_has_no_gravel_brand_leak(self, profile, parsed):
        profile['brand'] = 'roadielabs'
        profile['discipline'] = 'road'
        profile['target_race']['name'] = 'Gran Fondo Maryland'
        email = generate_personal_email(profile, parsed)
        assert 'Roadie Labs' in email
        assert 'roadielabs.com' in email
        assert 'Gravel God' not in email
        assert 'gravelgodcycling.com' not in email


def _plan_ir(tmp_path, field_test_weeks):
    import json
    weeks = [
        {'number': n, 'sessions': [
            {'type': 'ftp_test' if n in field_test_weeks else 'endurance',
             'is_field_test': n in field_test_weeks},
        ]}
        for n in range(1, 13)
    ]
    (tmp_path / 'plan_ir.json').write_text(json.dumps({'weeks': weeks}))
    return tmp_path


class TestRetestPromise:
    """The email may only promise a mid-plan retest the schedule contains.

    Retests are withheld for an explicit no-test answer or unresolved pain
    (2026-09-22 order); the email used to promise one whenever FTP was known.
    """

    @pytest.fixture
    def known_ftp(self, profile):
        profile['fitness_markers'] = {'ftp_watts': 245, 'ftp_estimated': False}
        return profile

    def test_promises_retest_when_scheduled(self, known_ftp, parsed, tmp_path):
        email = generate_personal_email(
            known_ftp, parsed, athlete_dir=_plan_ir(tmp_path, {1, 6}))
        assert 'retest mid-plan' in email

    def test_no_retest_promise_when_only_week_one_is_tested(
            self, known_ftp, parsed, tmp_path):
        email = generate_personal_email(
            known_ftp, parsed, athlete_dir=_plan_ir(tmp_path, {1}))
        assert 'retest' not in email
        assert '**Your zones are set.**' in email

    def test_no_retest_promise_without_a_built_plan(self, known_ftp, parsed):
        assert 'retest' not in generate_personal_email(known_ftp, parsed)


class TestEmailDeliveryCopy:
    def test_subject_no_exclamation(self):
        assert '!' not in EmailDelivery.SUBJECT
        assert EmailDelivery.SUBJECT == 'Your custom training plan is ready'

    def test_body_voice_rules(self):
        delivery = EmailDelivery()
        plain, html = delivery._build_email_body('Jesse Couch',
                                                 guide_url='https://example.com/guide')
        _assert_voice(plain, 'delivery plain text')
        _assert_voice(html, 'delivery html')
        assert '!' not in plain

    def test_body_signed_matti(self):
        delivery = EmailDelivery()
        plain, html = delivery._build_email_body('Jesse Couch')
        for body in (plain, html):
            assert 'Matti' in body
            assert 'Gravel God Coaching' in body

    def test_body_names_deliverables_and_first_action(self):
        delivery = EmailDelivery()
        plain, _ = delivery._build_email_body('Jesse Couch')
        assert 'guide' in plain.lower()
        assert 'read the phase overview' in plain.lower()
        assert 'reply to this email' in plain.lower()

    def test_roadie_sender_and_signature_have_no_gravel_brand_leak(self):
        delivery = EmailDelivery(brand='roadielabs')
        plain, html = delivery._build_email_body('Jesse Couch')
        assert delivery.from_email == 'coach@roadielabs.com'
        for body in (plain, html):
            assert 'Roadie Labs' in body
            assert 'Gravel God' not in body

    def test_delivery_cli_propagates_profile_brand(self):
        delivery = _email_delivery_for_profile({'brand': 'roadielabs'})
        plain, html = delivery._build_email_body('Jesse Couch')
        assert delivery.brand == 'roadielabs'
        assert delivery.from_email == 'coach@roadielabs.com'
        for body in (plain, html):
            assert 'Roadie Labs' in body
            assert 'Gravel God' not in body
